### ISSUE TITLE
Invalid stylus declaration! when using text-align

### ISSUE THREAD

**Issue by pdehaan** [jasongornall/stylushelp#23]
I seem to be getting an "Invalid stylus declaration" warning when using `text-align` in my stylus file and runnning `$ stylus-help simple_lint`...

Here's my _foo.styl_ file:
```
table.details-table
  width 100%

  th
    text-align start

  tbody th[scope="row"]
    width 10em
```

If I run the `stylus-help` script with the following args, I get an "Invalid stylus declaration!" warning:
```sh
$ stylus-help simple_lint foo.styl
```

And here is the output:
```json
{
   "foo.styl": [
      {
         "message": "Invalid stylus declaration!",
         "line": "text-align start",
         "line_num": 6
      }
   ]
}
```

**Comment by jasongornall** [comment]
good catch
